services:
  - type: web
    name: discord-cat-ai-bot
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        fromDatabase: false
        value: your_discord_bot_token_here
      - key: AI_API_KEY
        fromDatabase: false
        value: AIzaSyDtgKODGQeIGxNr2RSPQZJzF-Nh5k2KxFk
