services:
  - type: web
    name: discord-ai-bot
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        fromDatabase: false
        value: "MTM3NzgwOTMyMzI2NjE1MDUyMQ.GAaAsH.L8T5fMFwfLM2N_z4mK20rkpIn0vJR6D5YbGWQI"
      - key: AI_API_KEY
        fromDatabase: false
        value: "AIzaSyDtgKODGQeIGxNr2RSPQZJzF-Nh5k2KxFk"
    healthCheckPath: /
    port: 10000
